### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by Swati-totare**

### CODE REVIEW

**Review by kapil-padwekar — COMMENTED** [review]
Please do provide a description for the commit.

**Comment by Swati-totare** [comment]
> Please do provide a description for the commit.

Updated the last phrase of your code

**Comment by kapil-padwekar** [comment]
Hey, I am accepting it as it a very small change. Having said that I would advise you to always give a meaningful description.
Read https://www.freecodecamp.org/news/a-beginners-guide-to-git-how-to-write-a-good-commit-message/
I wish you good luck. Keep Learning!

**Comment by kapil-padwekar** [comment]
Improved UI text.

**Comment by Swati-totare** [comment]
Thank you I will keep your suggestion in mind

**Pull request merged**
